### ISSUE TITLE
Summary plots

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PyleoTutorials#2]
Work through an example to "pretty up" a summary plot for publication, with the various options. Can reuse the example in the Pyleoclim manuscript using Nino3.4 data.

It would be interesting to first show the default plot and look at ways to change some attributes.

**Comment by khider** [comment]
Done in [4bd50f](https://github.com/LinkedEarth/PyleoTutorials/commit/4bd50f32ff306b1cf74bc17626d1f30c9f5128c4)

**Comment by CommonClimate** [comment]
Pushed a few very minor edits in fd9da1a5b908747d1381272922c027ce3b557046. Main problem remains with Pyleoclim issue #243, awaiting resolution.

**Comment by CommonClimate** [comment]
@khider is this issue resolved now? I can't remember what the issue was but I seem to recall that @jordanplanders' gridspec additions to summary_plot did everything we needed them to.

**Comment by CommonClimate** [comment]
same as #30
